apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-xoc7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/bkorren-tenant/my-app/devfile-sample-python-basic-xoc7@sha256:91918ca2766ce0b00e54be6bde3f8d17a0932068b7e0629e8ede484166b653b1
        name: my-python
        resources: {}
status: {}
